config/routes.rb
Rails.application.routes.draw do
  root to: 'articles#index'
  resources :articles do
    resources :comments
  end
  resources :tags
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
  has_many :comments
  has_many :article_tags
  has_many :tags, through: :article_tags

  def tag_list
    tags.join(", ")
  end

  def tag_list=(tags_string)
    tag_names = tags_string.split(", ").map{ |s| s.strip.downcase }.uniq
    tag_names.each do |tag_name|
      tag = Tag.find_or_create_by(name: tag_name)
      self.tags << tag unless self.tags.include?(tag)
    end
  end
end

app/models/article_tag.rb
class ArticleTag < ApplicationRecord
  belongs_to :article
  belongs_to :tag
end

app/models/comment.rb
class Comment < ApplicationRecord
  belongs_to :article
end

app/models/tag.rb
class Tag < ApplicationRecord
  has_many :article_tags
  has_many :articles, through: :article_tags

  def to_s
    name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
  end
  def show
    @article = Article.find(params[:id])
    @comment = Comment.new
    @comment.article_id = @article.id
  end
  def new
    @article = Article.new
  end
  def create
    @article = Article.new(article_params)
    @article.save

    flash.notice = "Article '#{@article.title}' Created"

    redirect_to article_path(@article)
  end
  def edit
    @article = Article.find(params[:id])
  end
  def update
    @article = Article.find(params[:id])
    @article.update(article_params)

    flash.notice = "Article '#{@article.title}' Updated"

    redirect_to article_path(@article)
  end
  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    ArticleTag.where(article_id: params[:id]).destroy_all

    flash.notice = "Article '#{@article.title}' Deleted"

    redirect_to articles_path
  end

  private

  def article_params
    params.require(:article).permit(:title, :body, :tag_list)
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  def create
    @comment = Comment.new(comment_params)
    @comment.article_id = params[:article_id]
    @comment.save

    redirect_to article_path(@comment.article)
  end

  private

  def comment_params
    params.require(:comment).permit(:commenter_name, :body)
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  def index
    @tags = Tag.all.order(:name)
  end
  def show
    @tag = Tag.find(params[:id])
  end
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy
    ArticleTag.where(tag_id: params[:id]).destroy_all

    flash.notice = "Tag '#{@tag.name}' Deleted"

    redirect_to tags_path
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/articles_helper.rb
module ArticlesHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/tag_helper.rb
module TagHelper
end

app/views/articles/_comment.html.erb
<div>
  <h4>Comment by <%= comment.commenter_name %></h4>
  <p>Posted <%= distance_of_time_in_words(Time.now, comment.created_at) %> ago</p>
  <p class="comment"><%= comment.body %></p>
</div>

app/views/articles/_form.html.erb
<%= form_for(@article) do |f| %>
  <ul>
    <% @article.errors.full_messages.each do |error| %>
      <li>
        <%= error %>
      </li>
    <% end %>
  </ul>
  <p>
    <%= f.label :title %><br />
    <%= f.text_field :title %>
  </p>
  <p>
    <%= f.label :body %><br />
    <%= f.text_area :body %>
  </p>
  <p>
    <%= f.label :tag_list %>
    <%= f.text_field :tag_list %>
  </p>
  <p>
    <%= f.submit %>
  </p>
<% end %>

app/views/articles/edit.html.erb
<h1>Edit an Article</h1>

<%= render partial: 'form' %>

app/views/articles/index.html.erb
<h1>All Articles</h1>

<ul id="articles-links">
	<% @articles.each do |article| %>
	  <li>
		<%= link_to article.title, article_path(article), class: 'article_title' %>
	  </li>
	<% end %>
</ul>

<%= link_to "Create a New Article", new_article_path, class: "new_article" %>

app/views/articles/new.html.erb
<h1>Create a New Article</h1>

<%= render partial: 'form' %>

app/views/articles/show.html.erb
<h1><%= @article.title %></h1>
<p>
  Tags:
  <% @article.tags.order(:name).each do |tag| %>
      <%= link_to tag.name, tag_path(tag) %>
  <% end %>
</p>
<p><%= @article.body %></p>

<h3>Comments (<%= @article.comments.count %>)</h3>
<%= render partial: "comments/form" %>
<%= render partial: "articles/comment", collection: @article.comments.reverse %>

<%= link_to "<< Back to Articles List", articles_path, class: "top-button" %>
<%= link_to "Edit Article", edit_article_path(@article) %>
<%= link_to "Delete Article", article_path(@article), data: {confirm: "Do you really want to delete this article?"}, method: :delete %>

app/views/comments/_form.html.erb
<h3>Post a Comment</h3>

<%= form_for [ @article, @comment ] do |f| %>
  <p>
    <%= f.label :commenter_name, "Your Name" %><br />
    <%= f.text_field :commenter_name %>
  </p>
  <p>
    <%= f.label :body, "Your Comment" %><br />
    <%= f.text_field :body %>
  </p>
  <p>
    <%= f.submit "Submit" %>
  </p>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Blogger</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <p class="flash"><%= flash.notice %></p>
    <%= yield %>
  </body>
</html>

app/views/tags/index.html.erb
<h1>All Tags</h1>

<ul id="tags-links">
  <% @tags.each do |tag| %>
    <li>
      <%= link_to tag.name, tag_path(tag) %>
    </li>
  <% end %>
</ul>

app/views/tags/show.html.erb
<h1>Articles Tagged with '<%= @tag.name %>'</h1>

<ul>
  <% @tag.articles.each do |article| %>
    <li><%= link_to article.title, article_path(article) %></li>
  <% end %>
</ul>

<%= link_to "Delete Tag", tag_path(@tag), data: {confirm:  "Do you really want to delete this tag?"}, method: :delete %>